export interface DataPokmaswas {
  no: number;
  kabKota: string;
  namaKelompok: string;
  alamat: string;
  desa: string;
  kecamatan: string;
  ketua: string;
  noHp: string;
  lat: number;
  lon: number;
}

export const DATA_POKMASWAS: DataPokmaswas[] = [
  {
    no: 1,
    kabKota: "Kab. Malang",
    namaKelompok: "Licin Samudera Timur",
    alamat: "Lebakharjo, Ampelgading",
    desa: "Lebakharjo",
    kecamatan: "Ampelgading",
    ketua: "Tumiran / Soder",
    noHp: "62 823-3772-2446",
    lat: -8.3618,
    lon: 112.9485,
  },
  {
    no: 2,
    kabKota: "Kab. Malang",
    namaKelompok: "Bangkit",
    alamat: "Pujiharjo, Tirtoyudo",
    desa: "Pujiharjo",
    kecamatan: "Tirtoyudo",
    ketua: "Angga Prayoga",
    noHp: "62 823-3200-2525",
    lat: -8.3796,
    lon: 112.8967,
  },
  {
    no: 3,
    kabKota: "Kab. Malang",
    namaKelompok: "Bowele",
    alamat: "Purwodadi, Tirtoyudo",
    desa: "Purwodadi",
    kecamatan: "Tirtoyudo",
    ketua: "Kasembadan / Agung",
    noHp: "62 856-4657-1392",
    lat: -8.3711,
    lon: 112.8453,
  },
  {
    no: 4,
    kabKota: "Kab. Malang",
    namaKelompok: "Sido Lestari",
    alamat: "Sidoasri, Sumbermanjing Wetan",
    desa: "Sidoasri",
    kecamatan: "Sumbermanjing Wetan",
    ketua: "Sih Hariadi",
    noHp: "62 838-3465-8866",
    lat: -8.3845,
    lon: 112.7774,
  },
  {
    no: 5,
    kabKota: "Kab. Malang",
    namaKelompok: "Gatra Alam Lestari (GAL)",
    alamat: "Sitiarjo, Sumbermanjing Wetan",
    desa: "Sitiarjo",
    kecamatan: "Sumbermanjing Wetan",
    ketua: "Sumenggareng Budi L. / Enggar",
    noHp: "62 821-4054-6993",
    lat: -8.4359,
    lon: 112.6479,
  },
  {
    no: 6,
    kabKota: "Kab. Malang",
    namaKelompok: "Tamban Lestari",
    alamat: "Tambakrejo, Sumbermanjing",
    desa: "Tambakrejo",
    kecamatan: "Sumbermanjing",
    ketua: "Swasana Hari Darmawan",
    noHp: "62 822-2917-0413",
    lat: -8.417,
    lon: 112.7107,
  },
  {
    no: 7,
    kabKota: "Kab. Malang",
    namaKelompok: "Gatra Olah Alam Lestari (GOAL)",
    alamat: "Tambakrejo, Sumbermanjing Wetan",
    desa: "Tambakrejo",
    kecamatan: "Sumbermanjing Wetan",
    ketua: "Saptoyo",
    noHp: "62 813-3377-7689",
    lat: -8.43,
    lon: 112.6792,
  },
  {
    no: 8,
    kabKota: "Kab. Malang",
    namaKelompok: "Pilar Harapan",
    alamat: "Gajahrejo, Gedangan",
    desa: "Gajahrejo",
    kecamatan: "Gedangan",
    ketua: "Sutari",
    noHp: "62 812-8741-3091",
    lat: -8.4246,
    lon: 112.6385,
  },
  {
    no: 9,
    kabKota: "Kab. Malang",
    namaKelompok: "Tumpakrejo",
    alamat: "Tumpakrejo, Gedangan",
    desa: "Tumpakrejo",
    kecamatan: "Gedangan",
    ketua: "Sunari",
    noHp: "62 812-3394-2330",
    lat: -8.39,
    lon: 112.52,
  },
  {
    no: 10,
    kabKota: "Kab. Malang",
    namaKelompok: "Menuju Masyarakat Sejahtera (MESRA)",
    alamat: "Srigonco, Bantur",
    desa: "Srigonco",
    kecamatan: "Bantur",
    ketua: "Fathkurozi",
    noHp: "62 812-1736-0867",
    lat: -8.403,
    lon: 112.5392,
  },
  {
    no: 11,
    kabKota: "Kab. Malang",
    namaKelompok: "Mina Mulya",
    alamat: "Sumberbening, Bantur",
    desa: "Sumberbening",
    kecamatan: "Bantur",
    ketua: "Galito / Bagio",
    noHp: "62 813-7967-9403",
    lat: -8.3954,
    lon: 112.521,
  },
  {
    no: 12,
    kabKota: "Kab. Malang",
    namaKelompok: "Samudro Lestari",
    alamat: "Kedungsalam, Donomulyo",
    desa: "Kedungsalam",
    kecamatan: "Donomulyo",
    ketua: "Supiyat / Teguh",
    noHp: "62 858-6662-4886",
    lat: -8.3834,
    lon: 112.4242,
  },
  {
    no: 13,
    kabKota: "Kab. Malang",
    namaKelompok: "Trisakti",
    alamat: "Rekesan, Kromengan",
    desa: "Rekesan",
    kecamatan: "Kromengan",
    ketua: "Sukamdi",
    noHp: "62 812-1867-3107",
    lat: -8.34,
    lon: 112.31,
  },
  {
    no: 14,
    kabKota: "Kab. Malang",
    namaKelompok: "Mina Abadi",
    alamat: "Kaumrejo, Ngantang",
    desa: "Kaumrejo",
    kecamatan: "Ngantang",
    ketua: "Miskan",
    noHp: "62 823-3179-9143",
    lat: -7.87,
    lon: 112.36,
  },
  {
    no: 15,
    kabKota: "Kab. Malang",
    namaKelompok: "Singkil Park",
    alamat: "Kalirejo, Kalipare",
    desa: "Kalirejo",
    kecamatan: "Kalipare",
    ketua: "Muhammad Ya'i",
    noHp: "62 812-3496-4309",
    lat: -8.28,
    lon: 112.35,
  },
  {
    no: 16,
    kabKota: "Kab. Malang",
    namaKelompok: "Singkil Park",
    alamat: "Bendungrejo, Bantur",
    desa: "Bendungrejo",
    kecamatan: "Bantur",
    ketua: "Alex Yusnanto",
    noHp: "",
    lat: -8.36,
    lon: 112.39,
  },
  {
    no: 17,
    kabKota: "Kab. Malang",
    namaKelompok: "Jonggring Saloko Asri",
    alamat: "Mentaraman, Donomulyo",
    desa: "Mentaraman",
    kecamatan: "Donomulyo",
    ketua: "Suratno",
    noHp: "62 821-4336-3386",
    lat: -8.3788,
    lon: 112.3971,
  },
  {
    no: 18,
    kabKota: "Kab. Malang",
    namaKelompok: "Tirtamas",
    alamat: "Sanankerto, Turen",
    desa: "Sanankerto",
    kecamatan: "Turen",
    ketua: "Susiadi",
    noHp: "62 831-9290-6669",
    lat: -8.18,
    lon: 112.69,
  },
  {
    no: 19,
    kabKota: "Kab. Malang",
    namaKelompok: "Sari Mulyo",
    alamat: "Pandan Mulyo, Tajinan",
    desa: "Pandan Mulyo",
    kecamatan: "Tajinan",
    ketua: "Kusnadi",
    noHp: "",
    lat: -8.05,
    lon: 112.72,
  },
  {
    no: 20,
    kabKota: "Kab. Malang",
    namaKelompok: "Sumber Barokah",
    alamat: "Wringin Songo, Tumpang",
    desa: "Wringin Songo",
    kecamatan: "Tumpang",
    ketua: "Budi Purwoko",
    noHp: "",
    lat: -8.0,
    lon: 112.77,
  },
  {
    no: 21,
    kabKota: "Kab. Pasuruan",
    namaKelompok: "Unggul Jaya",
    alamat: "Desa Penunggul, Kec. Nguling",
    desa: "Penunggul",
    kecamatan: "Nguling",
    ketua: "Sofwatun Nisa",
    noHp: "",
    lat: -7.67,
    lon: 112.98,
  },
  {
    no: 22,
    kabKota: "Kab. Pasuruan",
    namaKelompok: "Alta Mina Lestari",
    alamat: "Dsn. Lampean, Ds. Kedawang, Kec. Nguling",
    desa: "Kedawang",
    kecamatan: "Nguling",
    ketua: "Amran Shodiq",
    noHp: "",
    lat: -7.665,
    lon: 112.975,
  },
  {
    no: 23,
    kabKota: "Kab. Pasuruan",
    namaKelompok: "Jumpinang Berkarya",
    alamat: "Desa Sumberrejo, Kec. Purwosari",
    desa: "Sumberrejo",
    kecamatan: "Purwosari",
    ketua: "Nanang Supriadi",
    noHp: "",
    lat: -7.75,
    lon: 112.73,
  },
  {
    no: 24,
    kabKota: "Kab. Pasuruan",
    namaKelompok: "Tinang Mina Unggul",
    alamat: "Desa Patuguran, Kec. Rejoso",
    desa: "Patuguran",
    kecamatan: "Rejoso",
    ketua: "Karyono",
    noHp: "",
    lat: -7.72,
    lon: 112.85,
  },
  {
    no: 25,
    kabKota: "Kab. Pasuruan",
    namaKelompok: "Ranu Lestari",
    alamat: "Dsn. Parasan, Ds. Grati Tunon",
    desa: "Grati Tunon",
    kecamatan: "Grati",
    ketua: "Suryanto",
    noHp: "",
    lat: -7.74,
    lon: 112.87,
  },
  {
    no: 36,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Juanda Lestari",
    alamat: "Desa Gisik Cemandi, Kec. Sedati",
    desa: "Gisik Cemandi",
    kecamatan: "Sedati",
    ketua: "Drs. Abdul Haris",
    noHp: "",
    lat: -7.38,
    lon: 112.77,
  },
  {
    no: 37,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Akar Delta Ujung",
    alamat: "Desa Kedung Pandan, Kec. Jabon",
    desa: "Kedung Pandan",
    kecamatan: "Jabon",
    ketua: "Baldowi",
    noHp: "",
    lat: -7.52,
    lon: 112.78,
  },
  {
    no: 38,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Berantas Lestari",
    alamat: "Desa Jeruk Legi, Kec. Balongbendo",
    desa: "Jeruk Legi",
    kecamatan: "Balongbendo",
    ketua: "Mudjiadi",
    noHp: "",
    lat: -7.48,
    lon: 112.6,
  },
  {
    no: 39,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Tirto Mas",
    alamat: "Desa Bogempinggir, Kec. Balongbendo",
    desa: "Bogempinggir",
    kecamatan: "Balongbendo",
    ketua: "Wahyu Ismawandik",
    noHp: "",
    lat: -7.485,
    lon: 112.605,
  },
  {
    no: 40,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Delta Samudra Timur",
    alamat: "Dusun Tanjungsari, Desa Kupang",
    desa: "Kupang",
    kecamatan: "Jabon",
    ketua: "Amin Tohari",
    noHp: "",
    lat: -7.46,
    lon: 112.8,
  },
  {
    no: 41,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Kalimas Surabaya",
    alamat: "Desa Penambangan, Kec. Balongbendo",
    desa: "Penambangan",
    kecamatan: "Balongbendo",
    ketua: "Agum Salim",
    noHp: "",
    lat: -7.475,
    lon: 112.595,
  },
  {
    no: 42,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Pucuan",
    alamat: "Dusun Pucuan, Kel. Gebang",
    desa: "Gebang",
    kecamatan: "Sidoarjo",
    ketua: "M. Zamroni",
    noHp: "",
    lat: -7.44,
    lon: 112.71,
  },
  {
    no: 43,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Lancar Jaya",
    alamat: "Desa Bluru Kidul, Kec. Sidoarjo",
    desa: "Bluru Kidul",
    kecamatan: "Sidoarjo",
    ketua: "Lukman Fauzi",
    noHp: "",
    lat: -7.455,
    lon: 112.715,
  },
  {
    no: 44,
    kabKota: "Kab. Sidoarjo",
    namaKelompok: "Ketingan Jaya",
    alamat: "Dusun Kepetingan, Desa Sawohan",
    desa: "Sawohan",
    kecamatan: "Buduran",
    ketua: "Achmad Syafi'i",
    noHp: "62 878-5162-9856",
    lat: -7.5,
    lon: 112.82,
  },
];

export const KABKOTA_WARNA: Record<string, string> = {
  "Kab. Malang": "#059669",
  "Kab. Pasuruan": "#0284c7",
  "Kab. Sidoarjo": "#d97706",
};
